name: 'GitHub Actions Weather Bot'
 
on:
  push:
  schedule:
    - cron: '0 21 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Result'
        run: bash ./weather.sh
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          serveraddress: smtp.163.com
          serverport: 465
          username: coderstephenlee@163.com
          password: Yqqlmgs1cl
          subject: Shanghai Weather Report
          body: file://result.html
          to: 13917732040@139.com
          from: GitHub Actions
          content_type: text/html
